apiVersion: v1
kind: Pod
metadata:
  generateName: pants-
spec:
  restartPolicy: Never
  imagePullSecrets:
    - name: docker-registry-cred # create using ~/github/abugov/research/playground/k8s/scripts/create_image_pull_secret.sh
  containers:
    - name: pants
      #image: ubuntu
      #command: ["bash", "-c", "echo HI"]
      image: ghcr.io/abugov/pants-example-jvm:main
      imagePullPolicy: Always
      command: ['bash', '-c', 'echo "build date: `cat /BUILD_DATE`" && cd example-jvm && git pull --ff-only && ./pants check :: ']
